import 'package:flutter/material.dart';
import '../models/beneficiary.dart';

class ImpactPage extends StatefulWidget { const ImpactPage({super.key}); @override State<ImpactPage> createState()=>_ImpactPageState(); }
class _ImpactPageState extends State<ImpactPage> {
 final _search=TextEditingController(); String _cause='All'; String _sort='Newest';
 final _items=const [Beneficiary(id:'1',name:'Rahul Kumar',cause:'Education',supportedYear:2025,contributionAmount:25000),Beneficiary(id:'2',name:'Priya Sharma',cause:'Healthcare',supportedYear:2024,contributionAmount:18000),Beneficiary(id:'3',name:'Amit Patel',cause:'Education',supportedYear:2025,contributionAmount:12000)];
 @override void dispose(){_search.dispose();super.dispose();}
 List<Beneficiary> get _filtered { final q=_search.text.toLowerCase(); final list=_items.where((x)=>(_cause=='All'||x.cause==_cause)&&(q.isEmpty||x.name.toLowerCase().contains(q))).toList(); list.sort((a,b){switch(_sort){case 'Name A–Z':return a.name.compareTo(b.name);case 'Highest amount':return b.contributionAmount.compareTo(a.contributionAmount);case 'Lowest amount':return a.contributionAmount.compareTo(b.contributionAmount);default:return b.supportedYear.compareTo(a.supportedYear);}});return list;}
 @override Widget build(BuildContext context){final items=_filtered;return Scaffold(appBar:AppBar(title:const Text('Our Impact')),body:ListView(padding:const EdgeInsets.fromLTRB(20,12,20,32),children:[Text('Lives touched through your contributions.',style:Theme.of(context).textTheme.bodyLarge),const SizedBox(height:20),TextField(key:const ValueKey('beneficiary_search'),controller:_search,onChanged:(_)=>setState((){}),decoration:const InputDecoration(prefixIcon:Icon(Icons.search),hintText:'Search by name',border:OutlineInputBorder())),const SizedBox(height:12),DropdownButtonFormField<String>(key:const ValueKey('beneficiary_cause_filter'),initialValue:_cause,decoration:const InputDecoration(labelText:'Cause',border:OutlineInputBorder()),items:const ['All','Education','Healthcare'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v)=>setState(()=>_cause=v??'All')),const SizedBox(height:12),DropdownButtonFormField<String>(key:const ValueKey('beneficiary_sort'),initialValue:_sort,decoration:const InputDecoration(labelText:'Sort',border:OutlineInputBorder()),items:const ['Newest','Name A–Z','Highest amount','Lowest amount'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v)=>setState(()=>_sort=v??'Newest')),const SizedBox(height:24),...items.map((x)=>Padding(padding:const EdgeInsets.only(bottom:16),child:_Card(x)))]));}
}
class _Card extends StatelessWidget {const _Card(this.x);final Beneficiary x;@override Widget build(BuildContext context)=>Card(child:Padding(padding:const EdgeInsets.all(18),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Container(height:150,width:double.infinity,decoration:BoxDecoration(color:const Color(0xFFFCE8C9),borderRadius:BorderRadius.circular(14)),child:const Icon(Icons.person_rounded,size:64,color:Color(0xFF6E1A14))),const SizedBox(height:16),Text(x.name,style:Theme.of(context).textTheme.titleLarge),const SizedBox(height:4),Text(x.cause),const SizedBox(height:14),Text('Supported in ${x.supportedYear}'),Text('₹${x.contributionAmount.toStringAsFixed(0)} Contribution'),const SizedBox(height:10),const Align(alignment:Alignment.centerRight,child:Text('View Story →'))])));}
