import { BadRequestException } from '@nestjs/common';
import { Timestamp } from 'firebase-admin/firestore';
import { FirestoreApplicationWindowsService } from './firestore-application-windows.service';
import { HelpApplicationTypeDto } from './dto/create-help-application.dto';

describe('FirestoreApplicationWindowsService',()=>{
  const type=HelpApplicationTypeDto.EDUCATION_ASSISTANCE;const admin={id:'a1',role:'ADMIN'};const identity={uid:'u1'} as any;
  function makeDb(data:any){const ref:any={get:jest.fn().mockResolvedValue({exists:Boolean(data),data:()=>data}),set:jest.fn(),update:jest.fn()};const query:any={get:jest.fn().mockResolvedValue({docs:data?[{id:type,data:()=>data}]:[]})};const db:any={collection:jest.fn(()=>({...query,doc:jest.fn(()=>ref)}))};return{db,ref};}
  it('lists windows and computes status',async()=>{const data={type,startsAt:Timestamp.fromDate(new Date(Date.now()-3600000)),registrationEndsAt:null,eventAt:null,closedAt:null,updatedById:'a1',updatedAt:Timestamp.now()};const {db}=makeDb(data);const users:any={getByFirebaseUid:jest.fn().mockResolvedValue(admin)};const result=await new FirestoreApplicationWindowsService({db} as any,users).list();expect(result.windows[0]).toEqual(expect.objectContaining({status:'OPEN',canApply:true}));});
  it('starts a window for an admin',async()=>{const {db,ref}=makeDb(null);const users:any={getByFirebaseUid:jest.fn().mockResolvedValue(admin)};const s=new FirestoreApplicationWindowsService({db} as any,users);const result=await s.start(identity,type,{type,startsAt:new Date(Date.now()-1000).toISOString()} as any);expect(result.status).toBe('OPEN');expect(ref.set).toHaveBeenCalled();});
  it('rejects mismatched and invalid schedules',async()=>{const {db}=makeDb(null);const users:any={getByFirebaseUid:jest.fn().mockResolvedValue(admin)};const s=new FirestoreApplicationWindowsService({db} as any,users);await expect(s.start(identity,type,{type:HelpApplicationTypeDto.PRATIBHA_SAMMAN} as any)).rejects.toBeInstanceOf(BadRequestException);await expect(s.start(identity,type,{type,startsAt:'bad'} as any)).rejects.toThrow('invalid date');});
  it('closes an existing window',async()=>{const data={type,startsAt:Timestamp.fromDate(new Date(Date.now()-3600000)),registrationEndsAt:null,eventAt:null,closedAt:null,updatedById:'a1',updatedAt:Timestamp.now()};const {db,ref}=makeDb(data);const users:any={getByFirebaseUid:jest.fn().mockResolvedValue(admin)};const s=new FirestoreApplicationWindowsService({db} as any,users);const result=await s.close(identity,type);expect(result.status).toBe('OPEN');expect(ref.update).toHaveBeenCalled();});
  it('enforces the acceptance window',async()=>{const {db}=makeDb(null);const users:any={getByFirebaseUid:jest.fn().mockResolvedValue(admin)};const s=new FirestoreApplicationWindowsService({db} as any,users);await expect(s.ensureAccepting(type)).rejects.toThrow('not currently');});
  it('rejects non-admins',async()=>{const {db}=makeDb(null);const users:any={getByFirebaseUid:jest.fn().mockResolvedValue({id:'u',role:'USER'})};const s=new FirestoreApplicationWindowsService({db} as any,users);await expect(s.start(identity,type,{type} as any)).rejects.toThrow('Administrator');});
});