import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { Timestamp } from 'firebase-admin/firestore';
import { randomUUID } from 'node:crypto';
import { FirebaseService } from '../firebase/firebase.service';
import { FirebaseIdentity } from '../auth/auth.types';
import { FirestoreUsersService } from '../users/firestore-users.service';
import { FirestoreMediaService } from '../media/firestore-media.service';
import { MediaService } from '../media/media.service';
import { FirestoreBeneficiariesService } from '../beneficiaries/firestore-beneficiaries.service';
import { CreateHelpApplicationDto, HelpApplicationTypeDto } from './dto/create-help-application.dto';
import { ResubmitHelpApplicationDto } from './dto/resubmit-help-application.dto';
import { ReviewHelpApplicationDto, HelpApplicationDecisionDto } from './dto/review-help-application.dto';
import { VoteHelpApplicationDto } from './dto/vote-help-application.dto';
import { UpdateHelpApplicationDto } from './dto/update-help-application.dto';
import { FirestoreApplicationWindowsService } from './firestore-application-windows.service';
import { FirestoreApplicationRulesService } from './firestore-application-rules.service';
import { createZip } from './certificate-photo-export.util';
import sharp from 'sharp';

type ApplicationStatus = 'SUBMITTED'|'UNDER_REVIEW'|'CLARIFICATION_REQUIRED'|'APPROVED_FOR_DONATION'|'REJECTED'|'CONSIDERED_FOR_SAMMAN'|'NOT_SELECTED';
type MediaRef = { mediaId: string };
type RuleAcceptance = { ruleId: string; ruleText: string };
type ApplicationDocument = {
  id:string; applicantId:string; applicantName:string; mobileNumber:string; email:string|null; address:string; city:string; state:string; pincode:string;
  type:HelpApplicationTypeDto; status:ApplicationStatus; requestedAmount:number|null; overallPercentage:number|null; approvedAmount:number|null;
  rejectionReason:string|null; clarification:string|null; motherName:string|null; fatherName:string|null; dateOfBirth:Timestamp|null;
  classStandard:string|null; schoolInstituteName:string|null; accomplishments:string|null; certificatePhotoMediaId:string|null; facePhotoMediaId:string|null;
  adminNote:string|null; submittedAt:Timestamp; reviewedAt:Timestamp|null; createdAt:Timestamp; updatedAt:Timestamp;
  media:MediaRef[]; ruleAcceptances:RuleAcceptance[];
};

@Injectable()
export class FirestoreHelpApplicationsService {
  constructor(
    private readonly firebase: FirebaseService,
    private readonly users: FirestoreUsersService,
    private readonly media: FirestoreMediaService,
    private readonly mediaService: MediaService,
    private readonly beneficiaries: FirestoreBeneficiariesService,
    private readonly windows: FirestoreApplicationWindowsService,
    private readonly rules: FirestoreApplicationRulesService,
  ) {}

  async create(identity: FirebaseIdentity, dto: CreateHelpApplicationDto) {
    const user = await this.user(identity);
    await this.windows.ensureAccepting(dto.type);
    this.validateApplicantDetails(dto); this.validateSubmission(dto.type,dto.requestedAmount,dto.mediaIds); this.validatePratibhaDetails(dto.type,dto);
    const accepted = await this.validateAcceptedRules(dto.type,dto.acceptedRuleIds);
    const media = await this.validateMedia(dto.mediaIds,user.id);
    const face = await this.validateFacePhoto(dto.facePhotoMediaId,user.id);
    const certificate = await this.validateCertificatePhoto(dto.type,dto.certificatePhotoMediaId,user.id,face);
    const id = randomUUID(); const now=Timestamp.now();
    const item:ApplicationDocument={id,applicantId:user.id,applicantName:dto.applicantName.trim(),mobileNumber:dto.mobileNumber.trim(),email:dto.email?.trim()||null,address:dto.address.trim(),city:dto.city.trim(),state:dto.state.trim(),pincode:dto.pincode.trim(),type:dto.type,status:'SUBMITTED',requestedAmount:dto.requestedAmount??null,overallPercentage:dto.overallPercentage??null,approvedAmount:null,rejectionReason:null,clarification:dto.clarification?.trim()||null,motherName:dto.motherName?.trim()||null,fatherName:dto.fatherName?.trim()||null,dateOfBirth:dto.dateOfBirth?Timestamp.fromDate(new Date(dto.dateOfBirth)):null,classStandard:dto.classStandard?.trim()||null,schoolInstituteName:dto.schoolInstituteName?.trim()||null,accomplishments:dto.accomplishments?.trim()||null,certificatePhotoMediaId:certificate,facePhotoMediaId:face,adminNote:null,submittedAt:now,reviewedAt:null,createdAt:now,updatedAt:now,media:media.map(mediaId=>({mediaId})),ruleAcceptances:accepted.map(rule=>({ruleId:rule.id,ruleText:rule.text}))};
    await this.firebase.db.collection('helpApplications').doc(id).set(item);
    return this.toResponse(item);
  }

  async listMine(identity:FirebaseIdentity){ const u=await this.user(identity); const s=await this.firebase.db.collection('helpApplications').where('applicantId','==',u.id).orderBy('createdAt','desc').get(); return this.toResponses(s.docs.map(d=>d.data() as ApplicationDocument)); }
  async findMine(identity:FirebaseIdentity,id:string){ const u=await this.user(identity); const item=await this.application(id); if(item.applicantId!==u.id) throw new NotFoundException('Application not found.'); return this.toResponse(item); }

  async updateMine(identity:FirebaseIdentity,id:string,dto:UpdateHelpApplicationDto){
    const u=await this.user(identity); const existing=await this.application(id); if(existing.applicantId!==u.id) throw new NotFoundException('Application not found.');
    if(['APPROVED_FOR_DONATION','CONSIDERED_FOR_SAMMAN','NOT_SELECTED'].includes(existing.status)) throw new BadRequestException('This application can no longer be edited.');
    await this.windows.ensureAccepting(existing.type); this.validateApplicantDetails(dto as any); this.validateSubmission(existing.type,dto.requestedAmount,dto.mediaIds); this.validatePratibhaDetails(existing.type,dto);
    const accepted=await this.validateAcceptedRules(existing.type,dto.acceptedRuleIds); const media=await this.validateMedia(dto.mediaIds,u.id); const face=await this.validateFacePhoto(dto.facePhotoMediaId,u.id); const certificate=await this.validateCertificatePhoto(existing.type,dto.certificatePhotoMediaId,u.id,face);
    const removed=existing.media.map(x=>x.mediaId).filter(x=>!media.includes(x)); const now=Timestamp.now();
    const next={...existing,applicantName:dto.applicantName.trim(),mobileNumber:dto.mobileNumber.trim(),email:dto.email?.trim()||null,address:dto.address.trim(),city:dto.city.trim(),state:dto.state.trim(),pincode:dto.pincode.trim(),status:'SUBMITTED' as ApplicationStatus,requestedAmount:dto.requestedAmount??null,overallPercentage:dto.overallPercentage??null,approvedAmount:null,rejectionReason:null,clarification:dto.clarification?.trim()||null,motherName:dto.motherName?.trim()||null,fatherName:dto.fatherName?.trim()||null,dateOfBirth:dto.dateOfBirth?Timestamp.fromDate(new Date(dto.dateOfBirth)):null,classStandard:dto.classStandard?.trim()||null,schoolInstituteName:dto.schoolInstituteName?.trim()||null,accomplishments:dto.accomplishments?.trim()||null,certificatePhotoMediaId:certificate,facePhotoMediaId:face,adminNote:null,reviewedAt:null,updatedAt:now,media:media.map(mediaId=>({mediaId})),ruleAcceptances:accepted.map(rule=>({ruleId:rule.id,ruleText:rule.text}))};
    const batch=this.firebase.db.batch(); batch.set(this.firebase.db.collection('helpApplications').doc(id),next); for(const vote of await this.firebase.db.collection('helpApplicationVotes').where('applicationId','==',id).get().then(s=>s.docs)) batch.delete(vote.ref); await batch.commit();
    for(const mediaId of removed) { try { await this.mediaService.deleteUserImage(mediaId,u.id); } catch {} }
    return this.toResponse(next);
  }

  async deleteMine(identity:FirebaseIdentity,id:string){const u=await this.user(identity);const x=await this.application(id);if(x.applicantId!==u.id)throw new NotFoundException('Application not found.');if(['APPROVED_FOR_DONATION','CONSIDERED_FOR_SAMMAN'].includes(x.status))throw new BadRequestException('This application can no longer be deleted.');await this.firebase.db.collection('helpApplications').doc(id).delete();const s=await this.firebase.db.collection('helpApplicationVotes').where('applicationId','==',id).get();if(s.size){const b=this.firebase.db.batch();s.docs.forEach(d=>b.delete(d.ref));await b.commit();}return{id,deleted:true};}

  async resubmit(identity:FirebaseIdentity,id:string,dto:ResubmitHelpApplicationDto){const u=await this.user(identity);const x=await this.application(id);if(x.applicantId!==u.id)throw new NotFoundException('Application not found.');await this.windows.ensureAccepting(x.type);if(x.status!=='REJECTED'&&x.status!=='CLARIFICATION_REQUIRED')throw new BadRequestException('Only rejected or clarification-requested applications can be resubmitted.');this.validateSubmission(x.type,dto.requestedAmount??x.requestedAmount??0,dto.mediaIds);const media=await this.validateMedia(dto.mediaIds,u.id);const certificate=await this.validateCertificatePhoto(x.type,dto.certificatePhotoMediaId,u.id);const accepted=await this.validateAcceptedRules(x.type,dto.acceptedRuleIds);const now=Timestamp.now();const next={...x,status:'SUBMITTED' as ApplicationStatus,requestedAmount:dto.requestedAmount??x.requestedAmount,overallPercentage:dto.overallPercentage??x.overallPercentage,approvedAmount:null,rejectionReason:null,clarification:dto.clarification.trim(),motherName:dto.motherName?.trim()||x.motherName,fatherName:dto.fatherName?.trim()||x.fatherName,dateOfBirth:dto.dateOfBirth?Timestamp.fromDate(new Date(dto.dateOfBirth)):x.dateOfBirth,classStandard:dto.classStandard?.trim()||x.classStandard,schoolInstituteName:dto.schoolInstituteName?.trim()||x.schoolInstituteName,accomplishments:dto.accomplishments?.trim()||x.accomplishments,certificatePhotoMediaId:certificate??x.certificatePhotoMediaId,adminNote:null,reviewedAt:null,updatedAt:now,media:media.map(mediaId=>({mediaId})),ruleAcceptances:accepted.map(rule=>({ruleId:rule.id,ruleText:rule.text}))};const b=this.firebase.db.batch();b.set(this.firebase.db.collection('helpApplications').doc(id),next);const votes=await this.firebase.db.collection('helpApplicationVotes').where('applicationId','==',id).get();votes.docs.forEach(d=>b.delete(d.ref));await b.commit();return this.toResponse(next);}

  async listForAdmin(type?:string,status?:string){const snap=await this.firebase.db.collection('helpApplications').get();let items=snap.docs.map(d=>d.data() as ApplicationDocument);if(type)items=items.filter(x=>x.type===type);if(status)items=items.filter(x=>x.status===status);items.sort((a,b)=>this.date(a.createdAt)-this.date(b.createdAt));const responses=await this.toAdminResponses(items);responses.sort((a,b)=>(b.overallPercentage??-1)-(a.overallPercentage??-1)||(type==='PRATIBHA_SAMMAN'?(b.voteAverage??-1)-(a.voteAverage??-1):0)||this.date(a.submittedAt)-this.date(b.submittedAt));return responses;}
  async adminSummary(type?:string){let items=(await this.firebase.db.collection('helpApplications').get()).docs.map(d=>d.data() as ApplicationDocument);if(type)items=items.filter(x=>x.type===type);const counts:Record<string,number>={};items.forEach(x=>counts[x.status]=(counts[x.status]??0)+1);const selected=(counts.APPROVED_FOR_DONATION??0)+(counts.CONSIDERED_FOR_SAMMAN??0);return{total:items.length,needsReview:(counts.SUBMITTED??0)+(counts.UNDER_REVIEW??0)+(counts.CLARIFICATION_REQUIRED??0),selected,rejected:counts.REJECTED??0,notSelected:counts.NOT_SELECTED??0,clarificationRequired:counts.CLARIFICATION_REQUIRED??0,byStatus:counts};}
  async photoManifest(type?:string,status?:string){let items=(await this.firebase.db.collection('helpApplications').get()).docs.map(d=>d.data() as ApplicationDocument);if(type)items=items.filter(x=>x.type===type);if(status)items=items.filter(x=>x.status===status);items.sort((a,b)=>this.name(a).localeCompare(this.name(b))||this.date(a.createdAt)-this.date(b.createdAt));return Promise.all(items.filter(x=>x.facePhotoMediaId||x.certificatePhotoMediaId).map(async x=>({id:x.id,name:x.applicantName||'Applicant',type:x.type,status:x.status,facePhoto:x.facePhotoMediaId?await this.mediaResponse(x.facePhotoMediaId):null,certificatePhoto:x.certificatePhotoMediaId?await this.mediaResponse(x.certificatePhotoMediaId):null})));}

  async certificatePhotoExportSummary(type=HelpApplicationTypeDto.PRATIBHA_SAMMAN,status='CONSIDERED_FOR_SAMMAN'){const items=await this.filtered(type,status);const missing=items.filter(x=>!x.certificatePhotoMediaId).map(x=>({id:x.id,name:x.applicantName||'Applicant'}));return{total:items.length,available:items.length-missing.length,missing,type,status};}
  async buildCertificatePhotoExport(type=HelpApplicationTypeDto.PRATIBHA_SAMMAN,status='CONSIDERED_FOR_SAMMAN'){const items=await this.filtered(type,status);const entries:Array<{name:string;data:Buffer}>=[];const manifest=['Serial,Application ID,Applicant Name,Status,Photo Filename'];let serial=0;for(const item of items){serial++;const name=item.applicantName||'Applicant';if(!item.certificatePhotoMediaId){manifest.push([serial,item.id,name,'MISSING_PHOTO',''].map(csv).join(','));continue;}const outputName=`${String(serial).padStart(3,'0')}_${safeFileName(name)}.jpg`;try{const m=await this.media.getById(item.certificatePhotoMediaId);const source=await this.mediaService.downloadImage(m.storageKey);const jpeg=await sharp(source).rotate().resize({width:1800,height:1800,fit:'inside',withoutEnlargement:true}).jpeg({quality:92,mozjpeg:true}).toBuffer();entries.push({name:outputName,data:jpeg});manifest.push([serial,item.id,name,item.status,outputName].map(csv).join(','));}catch{manifest.push([serial,item.id,name,'PHOTO_READ_FAILED',''].map(csv).join(','));}}entries.push({name:'manifest.csv',data:Buffer.from('\ufeff'+manifest.join('\n')+'\n','utf8')});return createZip(entries);}

  async vote(identity:FirebaseIdentity,id:string,dto:VoteHelpApplicationDto){const admin=await this.admin(identity);const x=await this.application(id);const ref=this.firebase.db.collection('helpApplicationVotes').doc(`${id}_${admin.id}`);const now=Timestamp.now();await ref.set({id:ref.id,applicationId:id,adminId:admin.id,score:dto.score,comment:dto.comment?.trim()||null,updatedAt:now,createdAt:now},{merge:true});if(x.status==='SUBMITTED')await this.firebase.db.collection('helpApplications').doc(id).update({status:'UNDER_REVIEW',updatedAt:now});return{ id:ref.id, applicationId:id, adminId:admin.id, score:dto.score, comment:dto.comment?.trim()||null, updatedAt:now.toDate()};}

  async review(id:string,dto:ReviewHelpApplicationDto){const x=await this.application(id);if(dto.decision===HelpApplicationDecisionDto.APPROVE){if(x.type===HelpApplicationTypeDto.PRATIBHA_SAMMAN)throw new BadRequestException('Pratibha Samman applications must use a Samman decision.');const amount=dto.approvedAmount??0;if(amount<=0||amount>Number(x.requestedAmount??0))throw new BadRequestException('Approved amount must be greater than zero and no more than the requested amount.');return this.updateStatus(id,'APPROVED_FOR_DONATION',amount,null,dto.note);}if(dto.decision===HelpApplicationDecisionDto.REJECT){if(!dto.reason?.trim())throw new BadRequestException('A rejection reason is required.');return this.updateStatus(id,'REJECTED',null,dto.reason.trim(),dto.note);}if(dto.decision===HelpApplicationDecisionDto.CLARIFICATION_REQUIRED){if(!dto.reason?.trim())throw new BadRequestException('Clarification details are required.');return this.updateStatus(id,'CLARIFICATION_REQUIRED',null,dto.reason.trim(),dto.note);}if(x.type!==HelpApplicationTypeDto.PRATIBHA_SAMMAN)throw new BadRequestException('Samman decisions are only valid for Pratibha Samman applications.');return this.updateStatus(id,dto.decision===HelpApplicationDecisionDto.CONSIDER_FOR_SAMMAN?'CONSIDERED_FOR_SAMMAN':'NOT_SELECTED',null,dto.reason?.trim()||null,dto.note);}

  private async updateStatus(id:string,status:ApplicationStatus,approvedAmount:number|null,reason:string|null,note?:string){const ref=this.firebase.db.collection('helpApplications').doc(id);const snap=await ref.get();if(!snap.exists)throw new NotFoundException('Application not found.');const x=snap.data() as ApplicationDocument;const now=Timestamp.now();const next={...x,status,approvedAmount,rejectionReason:reason,adminNote:note?.trim()||null,reviewedAt:now,updatedAt:now};await ref.set(next);if(status==='CONSIDERED_FOR_SAMMAN'&&x.type===HelpApplicationTypeDto.PRATIBHA_SAMMAN)await this.publishBeneficiary(next);return this.toAdminResponse(next);}

  private async publishBeneficiary(x:ApplicationDocument){const causeSnap=await this.firebase.db.collection('causes').where('slug','==','pratibha-samman').limit(1).get();if(causeSnap.empty)throw new BadRequestException('Pratibha Samman cause is not configured.');const cause=causeSnap.docs[0].data() as any;const story=['Pratibha Samman — 2025-26 batch',x.classStandard?`Class/Standard: ${x.classStandard}`:null,x.schoolInstituteName?`School/Institute: ${x.schoolInstituteName}`:null,x.accomplishments?`Achievements: ${x.accomplishments}`:null,x.adminNote?`Recognition note: ${x.adminNote}`:null].filter(Boolean).join('\n');const existing=await this.firebase.db.collection('beneficiaries').where('sourceApplicationId','==',x.id).limit(1).get();const id=existing.empty?randomUUID():existing.docs[0].id;const doc={id,sourceApplicationId:x.id,name:x.applicantName,photoUrl:null,story,supportedYear:2026,contributionAmount:'0',causeId:cause.id,organisationId:null,isActive:true,displayOrder:0,media: x.certificatePhotoMediaId?[{mediaId:x.certificatePhotoMediaId,purpose:'PROFILE',isPrimary:true,displayOrder:0}]:[],createdAt:new Date(),updatedAt:new Date()};await this.beneficiaries.syncBeneficiary(doc);}

  private async validateMedia(ids:string[],userId:string){const unique=[...new Set(ids??[])];if(!unique.length||unique.length>10)throw new BadRequestException('Upload between 1 and 10 supporting images.');const docs=await Promise.all(unique.map(id=>this.firebase.db.collection('media').doc(id).get()));if(docs.some(d=>!d.exists||String(d.data()?.uploadedById??'')!==userId))throw new BadRequestException('One or more supporting images are unavailable.');return unique;}
  private async validateFacePhoto(id:string|undefined,userId:string){if(!id)throw new BadRequestException('A clear face photo is required.');const d=await this.firebase.db.collection('media').doc(id).get();if(!d.exists||String(d.data()?.uploadedById??'')!==userId)throw new BadRequestException('The face photo is unavailable.');return id;}
  private async validateCertificatePhoto(type:string,id:string|undefined,userId:string,face?:string){if(type!==HelpApplicationTypeDto.PRATIBHA_SAMMAN)return null;const effective=id??face;if(!effective)throw new BadRequestException('A clear certificate photo is required for Pratibha Samman.');const d=await this.firebase.db.collection('media').doc(effective).get();if(!d.exists||String(d.data()?.uploadedById??'')!==userId)throw new BadRequestException('The certificate photo is unavailable.');return effective;}
  private async validateAcceptedRules(type:HelpApplicationTypeDto,ids:string[]){const rules=await this.rules.listForAcceptance(type);const expected=new Set(rules.map(x=>x.id));const accepted=new Set(ids??[]);if(accepted.size!==expected.size||[...expected].some(id=>!accepted.has(id)))throw new BadRequestException('Please acknowledge every current application rule before submitting.');return rules;}
  private async application(id:string){const d=await this.firebase.db.collection('helpApplications').doc(id).get();if(!d.exists)throw new NotFoundException('Application not found.');return d.data() as ApplicationDocument;}
  private async user(identity:FirebaseIdentity){return this.users.upsertFromIdentity(identity);}
  private async admin(identity:FirebaseIdentity){const u=await this.user(identity);if(u.role!=='ADMIN'&&u.role!=='SUPER_ADMIN')throw new BadRequestException('Administrator access is required.');return u;}
  private async filtered(type:string,status:string){let items=(await this.firebase.db.collection('helpApplications').get()).docs.map(d=>d.data() as ApplicationDocument);return items.filter(x=>x.type===type&&x.status===status).sort((a,b)=>this.name(a).localeCompare(this.name(b))||this.date(a.createdAt)-this.date(b.createdAt));}
  private validateApplicantDetails(dto:any){const mobile=dto.mobileNumber.trim(),pin=dto.pincode.trim();if(!dto.applicantName.trim()||!dto.address.trim()||!dto.city.trim()||!dto.state.trim())throw new BadRequestException('Name, address, city and state are required.');if(!/^\+?[0-9]{10,13}$/.test(mobile))throw new BadRequestException('Enter a valid mobile number.');if(!/^[0-9]{6}$/.test(pin))throw new BadRequestException('Enter a valid 6-digit PIN code.');}
  private validateSubmission(type:string,amount:number|undefined,ids:string[]){if(!ids?.length||ids.length>10)throw new BadRequestException('Upload between 1 and 10 supporting images.');if(type!==HelpApplicationTypeDto.PRATIBHA_SAMMAN&&(!amount||amount<=0))throw new BadRequestException('Requested amount must be greater than zero.');}
  private validatePratibhaDetails(type:string,dto:any){if(type!==HelpApplicationTypeDto.PRATIBHA_SAMMAN)return;const missing=[['motherName',dto.motherName],['fatherName',dto.fatherName],['dateOfBirth',dto.dateOfBirth],['classStandard',dto.classStandard],['schoolInstituteName',dto.schoolInstituteName],['certificatePhotoMediaId',dto.certificatePhotoMediaId]].filter(([,v])=>v==null||String(v).trim()==='').map(([n])=>n);if(missing.length)throw new BadRequestException('Pratibha Samman requires mother name, father name, date of birth, class/standard, school/institute and a clear certificate photo.');if(dto.dateOfBirth&&Number.isNaN(new Date(dto.dateOfBirth).getTime()))throw new BadRequestException('Date of birth is invalid.');}
  private async toResponses(items:ApplicationDocument[]){return Promise.all(items.map(x=>this.toResponse(x)));}
  private async toResponse(x:ApplicationDocument){return {...this.baseResponse(x),media:await Promise.all((x.media??[]).map(m=>this.mediaResponse(m.mediaId)))};}
  private async toAdminResponses(items:ApplicationDocument[]){return Promise.all(items.map(x=>this.toAdminResponse(x)));}
  private async toAdminResponse(x:ApplicationDocument){const votes=await this.firebase.db.collection('helpApplicationVotes').where('applicationId','==',x.id).orderBy('updatedAt','desc').get();const admins=await Promise.all(votes.docs.map(v=>this.users.getById(String(v.data().adminId))));return{...await this.toResponse(x),applicant:await this.users.getById(x.applicantId),votes:votes.docs.map((v,i)=>({id:v.id,adminId:v.data().adminId,adminName:admins[i]?.displayName??null,score:v.data().score,comment:v.data().comment,updatedAt:this.dateValue(v.data().updatedAt)})),voteAverage:votes.size?votes.docs.reduce((s,v)=>s+Number(v.data().score||0),0)/votes.size:null};}
  private baseResponse(x:ApplicationDocument){return{id:x.id,type:x.type,status:x.status,applicantName:x.applicantName,mobileNumber:x.mobileNumber,email:x.email,address:x.address,city:x.city,state:x.state,pincode:x.pincode,requestedAmount:x.requestedAmount,overallPercentage:x.overallPercentage,approvedAmount:x.approvedAmount,rejectionReason:x.rejectionReason,clarification:x.clarification,motherName:x.motherName,fatherName:x.fatherName,dateOfBirth:this.dateValue(x.dateOfBirth),classStandard:x.classStandard,schoolInstituteName:x.schoolInstituteName,accomplishments:x.accomplishments,certificatePhotoMediaId:x.certificatePhotoMediaId,facePhotoMediaId:x.facePhotoMediaId,facePhoto:null,certificatePhoto:null,adminNote:x.adminNote,submittedAt:this.dateValue(x.submittedAt),reviewedAt:this.dateValue(x.reviewedAt)};}
  private async mediaResponse(id:string){const m=await this.media.getById(id);const base=process.env.R2_PUBLIC_BASE_URL?.replace(/\/$/,'');return{id:m.id,url:base?base+'/'+m.storageKey:m.storageKey,mimeType:m.mimeType,width:m.width,height:m.height};}
  private date(v:unknown){return this.dateValue(v)?.getTime()??0;} private dateValue(v:any):Date|null{if(!v)return null;if(v instanceof Timestamp)return v.toDate();if(v instanceof Date)return v;return typeof v.toDate==='function'?v.toDate():new Date(v);}
  private name(x:ApplicationDocument){return x.applicantName||'Applicant';}
}
function csv(value:string|number){return `"${String(value).replace(/"/g,'""')}"`;}
function safeFileName(value:string){const cleaned=value.normalize('NFKC').replace(/[\\/:*?"<>|\\r\\n]+/g,' ').trim().replace(/\\s+/g,'_');return(cleaned||'Applicant').slice(0,80);}
